export type Database = {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          slug: string;
          owner_email: string;
          category: string;
          region: string;
          latitude: number | null;
          longitude: number | null;
          address: string | null;
          bio: string | null;
          approved: boolean;
          is_live: boolean;
          logo_url: string | null;
          instagram_handle: string | null;
          onboarding_complete: boolean;
          onboarding_step: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          owner_email: string;
          category: string;
          region?: string;
          latitude?: number | null;
          longitude?: number | null;
          address?: string | null;
          bio?: string | null;
          approved?: boolean;
          is_live?: boolean;
          logo_url?: string | null;
          instagram_handle?: string | null;
          onboarding_complete?: boolean;
          onboarding_step?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          owner_email?: string;
          category?: string;
          region?: string;
          latitude?: number | null;
          longitude?: number | null;
          address?: string | null;
          bio?: string | null;
          approved?: boolean;
          is_live?: boolean;
          logo_url?: string | null;
          instagram_handle?: string | null;
          onboarding_complete?: boolean;
          onboarding_step?: number;
          created_at?: string;
        };
      };
      campaigns: {
        Row: {
          id: string;
          brand_id: string;
          title: string;
          headline: string | null;
          about_brand: string | null;
          perk_description: string | null;
          perk_value: number | null;
          perk_type: 'gift_card' | 'experience' | 'product' | null;
          target_city: string | null;
          target_county: string | null;
          content_requirements: string | null;
          talking_points: string[] | null;
          inspiration: Record<string, unknown>[] | null;
          deliverables: Record<string, boolean> | null;
          creator_target: number;
          open_date: string | null;
          expression_deadline: string | null;
          content_deadline: string | null;
          campaign_type: 'brand' | 'community';
          campaign_image: string | null;
          status: 'draft' | 'active' | 'selecting' | 'live' | 'completed';
          min_level: number;
          required_tags: string[] | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          brand_id: string;
          title: string;
          headline?: string | null;
          about_brand?: string | null;
          perk_description?: string | null;
          perk_value?: number | null;
          perk_type?: 'gift_card' | 'experience' | 'product' | null;
          target_city?: string | null;
          target_county?: string | null;
          content_requirements?: string | null;
          talking_points?: string[] | null;
          inspiration?: Record<string, unknown>[] | null;
          deliverables?: Record<string, boolean> | null;
          creator_target?: number;
          open_date?: string | null;
          expression_deadline?: string | null;
          content_deadline?: string | null;
          campaign_type?: 'brand' | 'community';
          campaign_image?: string | null;
          status?: 'draft' | 'active' | 'selecting' | 'live' | 'completed';
          min_level?: number;
          required_tags?: string[] | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          brand_id?: string;
          title?: string;
          headline?: string | null;
          about_brand?: string | null;
          perk_description?: string | null;
          perk_value?: number | null;
          perk_type?: 'gift_card' | 'experience' | 'product' | null;
          target_city?: string | null;
          target_county?: string | null;
          content_requirements?: string | null;
          talking_points?: string[] | null;
          inspiration?: Record<string, unknown>[] | null;
          deliverables?: Record<string, boolean> | null;
          creator_target?: number;
          open_date?: string | null;
          expression_deadline?: string | null;
          content_deadline?: string | null;
          campaign_type?: 'brand' | 'community';
          campaign_image?: string | null;
          status?: 'draft' | 'active' | 'selecting' | 'live' | 'completed';
          min_level?: number;
          required_tags?: string[] | null;
          created_at?: string;
          created_by?: string | null;
        };
      };
      applications: {
        Row: {
          id: string;
          campaign_id: string;
          creator_id: string;
          pitch: string | null;
          status: 'interested' | 'selected' | 'confirmed' | 'declined';
          applied_at: string;
          selected_at: string | null;
          confirmed_at: string | null;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          creator_id: string;
          pitch?: string | null;
          status?: 'interested' | 'selected' | 'confirmed' | 'declined';
          applied_at?: string;
          selected_at?: string | null;
          confirmed_at?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          creator_id?: string;
          pitch?: string | null;
          status?: 'interested' | 'selected' | 'confirmed' | 'declined';
          applied_at?: string;
          selected_at?: string | null;
          confirmed_at?: string | null;
        };
      };
      participations: {
        Row: {
          id: string;
          application_id: string;
          campaign_id: string;
          creator_id: string;
          perk_sent: boolean;
          perk_sent_at: string | null;
          reel_url: string | null;
          reel_submitted_at: string | null;
          reach: number | null;
          likes: number | null;
          comments: number | null;
          views: number | null;
          status: 'confirmed' | 'visited' | 'content_submitted' | 'completed' | 'overdue';
          completion_rate_snapshot: number | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          campaign_id: string;
          creator_id: string;
          perk_sent?: boolean;
          perk_sent_at?: string | null;
          reel_url?: string | null;
          reel_submitted_at?: string | null;
          reach?: number | null;
          likes?: number | null;
          comments?: number | null;
          views?: number | null;
          status?: 'confirmed' | 'visited' | 'content_submitted' | 'completed' | 'overdue';
          completion_rate_snapshot?: number | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          campaign_id?: string;
          creator_id?: string;
          perk_sent?: boolean;
          perk_sent_at?: string | null;
          reel_url?: string | null;
          reel_submitted_at?: string | null;
          reach?: number | null;
          likes?: number | null;
          comments?: number | null;
          views?: number | null;
          status?: 'confirmed' | 'visited' | 'content_submitted' | 'completed' | 'overdue';
          completion_rate_snapshot?: number | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      creators: {
        Row: {
          id: string;
          name: string;
          instagram_handle: string;
          follower_count: string | null;
          code: string;
          email: string;
          approved: boolean;
          onboarding_complete: boolean;
          avatar_url: string | null;
          address: string | null;
          latitude: number | null;
          longitude: number | null;
          created_at: string;
          level: number;
          level_name: string;
          total_reels: number;
          average_rating: number;
          current_streak: number;
          longest_streak: number;
          last_reel_month: string | null;
          profile_complete: boolean;
          display_name: string | null;
          bio: string | null;
          completion_rate: number;
          total_campaigns: number;
          completed_campaigns: number;
          instagram_connected: boolean;
          instagram_access_token: string | null;
          phone: string | null;
          referred_by: string | null;
          date_of_birth: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          instagram_handle: string;
          follower_count?: string | null;
          code: string;
          email: string;
          approved?: boolean;
          onboarding_complete?: boolean;
          avatar_url?: string | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
          level?: number;
          level_name?: string;
          total_reels?: number;
          average_rating?: number;
          current_streak?: number;
          longest_streak?: number;
          last_reel_month?: string | null;
          profile_complete?: boolean;
          display_name?: string | null;
          bio?: string | null;
          completion_rate?: number;
          total_campaigns?: number;
          completed_campaigns?: number;
          instagram_connected?: boolean;
          instagram_access_token?: string | null;
          phone?: string | null;
          referred_by?: string | null;
          date_of_birth?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          instagram_handle?: string;
          follower_count?: string | null;
          code?: string;
          email?: string;
          approved?: boolean;
          onboarding_complete?: boolean;
          avatar_url?: string | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
          level?: number;
          level_name?: string;
          total_reels?: number;
          average_rating?: number;
          current_streak?: number;
          longest_streak?: number;
          last_reel_month?: string | null;
          profile_complete?: boolean;
          display_name?: string | null;
          bio?: string | null;
          completion_rate?: number;
          total_campaigns?: number;
          completed_campaigns?: number;
          instagram_connected?: boolean;
          instagram_access_token?: string | null;
          phone?: string | null;
          referred_by?: string | null;
          date_of_birth?: string | null;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          user_type: string;
          message: string;
          read: boolean;
          email_sent: boolean;
          email_type: string | null;
          email_meta: Record<string, unknown> | null;
          campaign_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          user_type: string;
          message: string;
          read?: boolean;
          email_sent?: boolean;
          email_type?: string | null;
          email_meta?: Record<string, unknown> | null;
          campaign_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          user_type?: string;
          message?: string;
          read?: boolean;
          email_sent?: boolean;
          email_type?: string | null;
          email_meta?: Record<string, unknown> | null;
          campaign_id?: string | null;
          created_at?: string;
        };
      };
      disputes: {
        Row: {
          id: string;
          claim_id: string;
          reporter_role: 'creator' | 'business';
          message: string;
          resolved: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          claim_id: string;
          reporter_role: 'creator' | 'business';
          message: string;
          resolved?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          claim_id?: string;
          reporter_role?: 'creator' | 'business';
          message?: string;
          resolved?: boolean;
          created_at?: string;
        };
      };
    };
  };
};

export type UserRole = 'admin' | 'creator' | 'business';
