export type Database = {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          name: string;
          slug: string;
          owner_email: string;
          category: string;
          region: string;
          latitude: number | null;
          longitude: number | null;
          address: string | null;
          bio: string | null;
          approved: boolean;
          disapproved: boolean;
          is_live: boolean;
          logo_url: string | null;
          instagram_handle: string | null;
          onboarding_complete: boolean;
          onboarding_step: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          owner_email: string;
          category: string;
          region?: string;
          latitude?: number | null;
          longitude?: number | null;
          address?: string | null;
          bio?: string | null;
          approved?: boolean;
          disapproved?: boolean;
          is_live?: boolean;
          logo_url?: string | null;
          instagram_handle?: string | null;
          onboarding_complete?: boolean;
          onboarding_step?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          owner_email?: string;
          category?: string;
          region?: string;
          latitude?: number | null;
          longitude?: number | null;
          address?: string | null;
          bio?: string | null;
          approved?: boolean;
          disapproved?: boolean;
          is_live?: boolean;
          logo_url?: string | null;
          instagram_handle?: string | null;
          onboarding_complete?: boolean;
          onboarding_step?: number;
          created_at?: string;
        };
      };
      offers: {
        Row: {
          id: string;
          business_id: string;
          description: string;
          offer_type: string | null;
          offer_item: string | null;
          generated_title: string | null;
          content_type: string | null;
          specific_ask: string | null;
          offer_photo_url: string | null;
          min_level: number;
          monthly_cap: number | null;
          is_live: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          description: string;
          offer_type?: string | null;
          offer_item?: string | null;
          generated_title?: string | null;
          content_type?: string | null;
          specific_ask?: string | null;
          offer_photo_url?: string | null;
          min_level?: number;
          monthly_cap?: number | null;
          is_live?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          description?: string;
          offer_type?: string | null;
          offer_item?: string | null;
          generated_title?: string | null;
          content_type?: string | null;
          specific_ask?: string | null;
          offer_photo_url?: string | null;
          min_level?: number;
          monthly_cap?: number | null;
          is_live?: boolean;
          created_at?: string;
        };
      };
      creators: {
        Row: {
          id: string;
          name: string;
          instagram_handle: string;
          follower_count: string | null;
          code: string;
          email: string;
          approved: boolean;
          disapproved: boolean;
          onboarding_complete: boolean;
          avatar_url: string | null;
          address: string | null;
          latitude: number | null;
          longitude: number | null;
          created_at: string;
          level: number;
          level_name: string;
          total_reels: number;
          average_rating: number;
          current_streak: number;
          longest_streak: number;
          last_reel_month: string | null;
          profile_complete: boolean;
          display_name: string | null;
          bio: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          instagram_handle: string;
          follower_count?: string | null;
          code: string;
          email: string;
          approved?: boolean;
          disapproved?: boolean;
          onboarding_complete?: boolean;
          avatar_url?: string | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
          level?: number;
          level_name?: string;
          total_reels?: number;
          average_rating?: number;
          current_streak?: number;
          longest_streak?: number;
          last_reel_month?: string | null;
          profile_complete?: boolean;
          display_name?: string | null;
          bio?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          instagram_handle?: string;
          follower_count?: string | null;
          code?: string;
          email?: string;
          approved?: boolean;
          disapproved?: boolean;
          onboarding_complete?: boolean;
          avatar_url?: string | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          created_at?: string;
          level?: number;
          level_name?: string;
          total_reels?: number;
          average_rating?: number;
          current_streak?: number;
          longest_streak?: number;
          last_reel_month?: string | null;
          profile_complete?: boolean;
          display_name?: string | null;
          bio?: string | null;
        };
      };
      claims: {
        Row: {
          id: string;
          creator_id: string;
          offer_id: string;
          business_id: string;
          status: string;
          qr_token: string;
          qr_expires_at: string;
          claimed_at: string;
          redeemed_at: string | null;
          reel_url: string | null;
          reel_due_at: string | null;
          month: string;
        };
        Insert: {
          id?: string;
          creator_id: string;
          offer_id: string;
          business_id: string;
          status?: string;
          qr_token: string;
          qr_expires_at: string;
          claimed_at?: string;
          redeemed_at?: string | null;
          reel_url?: string | null;
          reel_due_at?: string | null;
          month: string;
        };
        Update: {
          id?: string;
          creator_id?: string;
          offer_id?: string;
          business_id?: string;
          status?: string;
          qr_token?: string;
          qr_expires_at?: string;
          claimed_at?: string;
          redeemed_at?: string | null;
          reel_url?: string | null;
          reel_due_at?: string | null;
          month?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          user_type: string;
          message: string;
          read: boolean;
          email_sent: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          user_type: string;
          message: string;
          read?: boolean;
          email_sent?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          user_type?: string;
          message?: string;
          read?: boolean;
          email_sent?: boolean;
          created_at?: string;
        };
      };
      disputes: {
        Row: {
          id: string;
          claim_id: string;
          reporter_role: 'creator' | 'business';
          message: string;
          resolved: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          claim_id: string;
          reporter_role: 'creator' | 'business';
          message: string;
          resolved?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          claim_id?: string;
          reporter_role?: 'creator' | 'business';
          message?: string;
          resolved?: boolean;
          created_at?: string;
        };
      };
    };
  };
};

export type UserRole = 'admin' | 'creator' | 'business';
